// Theme definitions for the 6 built-in themes
export const THEMES = {
    1: {
        name: 'Midnight Rose',
        name_ar: 'وردة منتصف الليل',
        light: {
            primary: '#2d1b4e',
            secondary: '#c62e65',
            background: '#faf7fc',
            text: '#1e1233',
            card: '#f0eaf6',
            accent: '#c62e65',
        },
        dark: {
            primary: '#e8a0bf',
            secondary: '#c62e65',
            background: '#13091f',
            text: '#ede4f5',
            card: '#1e1233',
            accent: '#c62e65',
        },
    },
    2: {
        name: 'Dark Burgundy',
        name_ar: 'عنابي داكن',
        light: {
            primary: '#2e0003',
            secondary: '#210b0f',
            background: '#f5f0ee',
            text: '#2e0003',
            card: '#ffffff',
            accent: '#8b2030',
        },
        dark: {
            primary: '#e8b4b8',
            secondary: '#8b2030',
            background: '#210b0f',
            text: '#f0e0e2',
            card: '#3a1518',
            accent: '#c4434f',
        },
    },
    3: {
        name: 'Midnight Gold',
        name_ar: 'أزرق ذهبي',
        light: {
            primary: '#10202d',
            secondary: '#c7a667',
            background: '#f7f7f7',
            text: '#10202d',
            card: '#ffffff',
            accent: '#b89840',
        },
        dark: {
            primary: '#c7a667',
            secondary: '#8b7444',
            background: '#10202d',
            text: '#e8edf2',
            card: '#1b3142',
            accent: '#d4b87a',
        },
    },
    4: {
        name: 'Emerald Nature',
        name_ar: 'زمرد طبيعي',
        light: {
            primary: '#02110c',
            secondary: '#1a422f',
            background: '#f3ebd6',
            text: '#02110c',
            card: '#faf6ea',
            accent: '#2d6b48',
        },
        dark: {
            primary: '#a8d5b8',
            secondary: '#1a422f',
            background: '#02110c',
            text: '#e8f0e0',
            card: '#0d2a1c',
            accent: '#3d8a5c',
        },
    },
    5: {
        name: 'Velvet Mauve',
        name_ar: 'مخمل وردي',
        light: {
            primary: '#321622',
            secondary: '#653b4e',
            background: '#f4d9cc',
            text: '#321622',
            card: '#fae8e0',
            accent: '#653b4e',
        },
        dark: {
            primary: '#e0b0c0',
            secondary: '#653b4e',
            background: '#321622',
            text: '#f0d8e0',
            card: '#482838',
            accent: '#a06880',
        },
    },
    6: {
        name: 'Coffee Brown',
        name_ar: 'بني قهوة',
        light: {
            primary: '#33130b',
            secondary: '#8d3b1e',
            background: '#f1f3dc',
            text: '#33130b',
            card: '#faf8e8',
            accent: '#8d3b1e',
        },
        dark: {
            primary: '#e0c4a0',
            secondary: '#8d3b1e',
            background: '#33130b',
            text: '#f0e4d0',
            card: '#4a2515',
            accent: '#c06030',
        },
    },
} as const;

export type ThemeId = keyof typeof THEMES;
